# Generated by Django 5.2.3 on 2025-07-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_match_points_history_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='points_team1',
            field=models.IntegerField(default=0, verbose_name='Points for Team 1'),
        ),
        migrations.AddField(
            model_name='match',
            name='points_team2',
            field=models.IntegerField(default=0, verbose_name='Points for Team 2'),
        ),
    ]
