# Generated by Django 5.2.3 on 2025-07-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_match_points_team1_match_points_team2'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
    ]
