# Generated by Django 5.2.3 on 2025-07-05 12:34

from django.db import migrations, models

def set_default_description(apps, schema_editor):
    Match = apps.get_model('tournaments', 'Match')
    Match.objects.filter(description='').update(description='No description')

class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_match_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='description',
            field=models.CharField(blank=True, default='No description', max_length=255, verbose_name='Description'),
        ),
        migrations.RunPython(set_default_description),
    ]
