# Generated by Django 5.2.3 on 2025-07-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_match_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='volleyball_player1_team1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Volleyball Player 1 (Team 1)'),
        ),
        migrations.AddField(
            model_name='match',
            name='volleyball_player1_team2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Volleyball Player 1 (Team 2)'),
        ),
        migrations.AddField(
            model_name='match',
            name='volleyball_player2_team1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Volleyball Player 2 (Team 1)'),
        ),
        migrations.AddField(
            model_name='match',
            name='volleyball_player2_team2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Volleyball Player 2 (Team 2)'),
        ),
        migrations.AddField(
            model_name='match',
            name='volleyball_player3_team1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Volleyball Player 3 (Team 1)'),
        ),
        migrations.AddField(
            model_name='match',
            name='volleyball_player3_team2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Volleyball Player 3 (Team 2)'),
        ),
        migrations.AddField(
            model_name='match',
            name='volleyball_player4_team1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Volleyball Player 4 (Team 1)'),
        ),
        migrations.AddField(
            model_name='match',
            name='volleyball_player4_team2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Volleyball Player 4 (Team 2)'),
        ),
        migrations.AddField(
            model_name='match',
            name='volleyball_player5_team1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Volleyball Player 5 (Team 1)'),
        ),
        migrations.AddField(
            model_name='match',
            name='volleyball_player5_team2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Volleyball Player 5 (Team 2)'),
        ),
        migrations.AddField(
            model_name='match',
            name='volleyball_player6_team1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Volleyball Player 6 (Team 1)'),
        ),
        migrations.AddField(
            model_name='match',
            name='volleyball_player6_team2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Volleyball Player 6 (Team 2)'),
        ),
    ]
