# Generated by Django 5.2.3 on 2025-06-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_match_status_match_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='total_points',
            field=models.IntegerField(default=21),
        ),
    ]
