# Generated by Django 5.2.3 on 2025-07-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_match_volleyball_player1_team1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='throwball_player1_team1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Throwball Player 1 (Team 1)'),
        ),
        migrations.AddField(
            model_name='match',
            name='throwball_player1_team2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Throwball Player 1 (Team 2)'),
        ),
        migrations.AddField(
            model_name='match',
            name='throwball_player2_team1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Throwball Player 2 (Team 1)'),
        ),
        migrations.AddField(
            model_name='match',
            name='throwball_player2_team2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Throwball Player 2 (Team 2)'),
        ),
        migrations.AddField(
            model_name='match',
            name='throwball_player3_team1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Throwball Player 3 (Team 1)'),
        ),
        migrations.AddField(
            model_name='match',
            name='throwball_player3_team2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Throwball Player 3 (Team 2)'),
        ),
        migrations.AddField(
            model_name='match',
            name='throwball_player4_team1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Throwball Player 4 (Team 1)'),
        ),
        migrations.AddField(
            model_name='match',
            name='throwball_player4_team2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Throwball Player 4 (Team 2)'),
        ),
        migrations.AddField(
            model_name='match',
            name='throwball_player5_team1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Throwball Player 5 (Team 1)'),
        ),
        migrations.AddField(
            model_name='match',
            name='throwball_player5_team2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Throwball Player 5 (Team 2)'),
        ),
        migrations.AddField(
            model_name='match',
            name='throwball_player6_team1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Throwball Player 6 (Team 1)'),
        ),
        migrations.AddField(
            model_name='match',
            name='throwball_player6_team2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Throwball Player 6 (Team 2)'),
        ),
        migrations.AddField(
            model_name='match',
            name='throwball_player7_team1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Throwball Player 7 (Team 1)'),
        ),
        migrations.AddField(
            model_name='match',
            name='throwball_player7_team2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Throwball Player 7 (Team 2)'),
        ),
        migrations.AddField(
            model_name='match',
            name='throwball_player8_team1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Throwball Player 8 (Team 1)'),
        ),
        migrations.AddField(
            model_name='match',
            name='throwball_player8_team2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Throwball Player 8 (Team 2)'),
        ),
        migrations.AddField(
            model_name='match',
            name='throwball_player9_team1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Throwball Player 9 (Team 1)'),
        ),
        migrations.AddField(
            model_name='match',
            name='throwball_player9_team2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Throwball Player 9 (Team 2)'),
        ),
    ]
