# Generated by Django 5.2.3 on 2025-06-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_match_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='points_history_json',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
