# Generated by Django 5.2.3 on 2025-07-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_match_kabaddi_player1_team1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='kabaddi_player_status_json',
            field=models.TextField(blank=True, default='{}', help_text='JSON dict of player in/out status for Kabaddi'),
        ),
    ]
