# Generated by Django 5.2.3 on 2025-07-12 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_match_kabaddi_player_status_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='kabaddi_player_status_json',
        ),
    ]
