# Generated by Django 5.2.3 on 2025-07-11 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0008_match_kabaddi_player1_team1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KabaddiRaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raid_number', models.PositiveIntegerField()),
                ('raider', models.CharField(max_length=100)),
                ('defenders', models.JSONField(blank=True, default=list, help_text='List of defenders involved')),
                ('result', models.CharField(choices=[('success', 'Successful Raid'), ('tackle', 'Tackle by Defenders'), ('empty', 'Empty Raid'), ('bonus', 'Bonus Point'), ('allout', 'All-Out'), ('super_raid', 'Super Raid'), ('super_tackle', 'Super Tackle'), ('out_of_bound', 'Out of Bound'), ('do_or_die', 'Do-or-Die Raid'), ('revival', 'Player Revival')], max_length=20)),
                ('points_team1', models.IntegerField(default=0)),
                ('points_team2', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('extra_info', models.JSONField(blank=True, default=dict, help_text='Any extra info for this raid event')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kabaddi_raids', to='tournaments.match')),
            ],
            options={
                'ordering': ['raid_number'],
                'unique_together': {('match', 'raid_number')},
            },
        ),
    ]
