# Generated by Django 5.2.3 on 2025-07-12 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KabaddiRaid',
        ),
    ]
